Repository Azure/ms-rest-nodeauth, pull requests merged in 2018-11, with the labels that each got.

#30 Rename package to "@azure/ms-rest-nodeauth"
  Changelog.md
  lib/credentials/applicationTokenCredentials.ts
  lib/credentials/deviceTokenCredentials.ts
  lib/credentials/keyVaultFactory.ts
  lib/credentials/msiAppServiceTokenCredentials.ts
  lib/credentials/msiTokenCredentials.ts
  lib/credentials/msiVmTokenCredentials.ts
  lib/credentials/tokenClientCredentials.ts
  lib/credentials/tokenCredentialsBase.ts
  lib/credentials/topicCredentials.ts
  lib/credentials/userTokenCredentials.ts
  lib/login.ts
  lib/subscriptionManagement/subscriptionUtils.ts
  package-lock.json
  package.json
  test/credentials/msiAppServiceTokenCredentialTests.ts
  test/credentials/msiVmTokenCredentialTests.ts
Labels: in progress

#33 Remove Travis configuration and add no-return-await TS lint rule
  .travis.yml
  tslint.json
Labels: Unplanned-Sprint-126, in progress

#34 Update missing references in samples
  README.md
Labels: Unplanned-Sprint-126, in progress

#36 Add rollup
  .gitignore
  package-lock.json
  package.json
  rollup.config.js
Labels: Planned-Sprint-127, Started-Sprint-127, in progress

#38 Add code owners and issue template
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  package.json
Labels: Planned-Sprint-127, in progress

#39 Fix incorrect path to the main file
  package.json
Labels: Planned-Sprint-127, in progress
